import type { Target } from './targets.js'
import type { Toolchain } from './toolchain.js'

export interface Emulator {
    /** Path of the qemu-user binary */
    path: string
    /** CPU model, or undefined for QEMU's default */
    cpu?: string
}

export interface Setup {
    target: Target
    toolchain: Toolchain
    sysroot: string
    /** null when the target runs natively */
    emulator: Emulator | null
}

export interface GeneratedFiles {
    toolchainFile: string
    mesonCrossFile: string
}

function emulatorCommand({ emulator, sysroot }: Setup): string[] | null {
    if (emulator === null) {
        return null
    }
    const cpu = emulator.cpu !== undefined ? ['-cpu', emulator.cpu] : []
    return [emulator.path, '-L', sysroot, ...cpu]
}

/** The compiler invocation with every flag that selects the target */
function compilerCommand(toolchain: Toolchain, compiler: string): string[] {
    return [
        compiler,
        ...(toolchain.compilerTarget !== undefined
            ? [`--target=${toolchain.compilerTarget}`]
            : []),
        ...toolchain.flags,
    ]
}

function cmakeQuote(value: string): string {
    return `"${value.replace(/[\\"$]/g, '\\$&')}"`
}

export function cmakeToolchainFile(setup: Setup): string {
    const { target, toolchain, sysroot } = setup
    const { programs } = toolchain
    const emulator = emulatorCommand(setup)
    const lines = [
        `# Generated by cross-compile-action for ${target.triple}: ${target.name}`,
        'set(CMAKE_SYSTEM_NAME Linux)',
        `set(CMAKE_SYSTEM_PROCESSOR ${cmakeQuote(target.cmakeProcessor)})`,
        '',
        `set(CMAKE_C_COMPILER ${cmakeQuote(programs.cc)})`,
        `set(CMAKE_CXX_COMPILER ${cmakeQuote(programs.cxx)})`,
    ]
    if (toolchain.compilerTarget !== undefined) {
        lines.push(
            `set(CMAKE_C_COMPILER_TARGET ${cmakeQuote(toolchain.compilerTarget)})`,
            `set(CMAKE_CXX_COMPILER_TARGET ${cmakeQuote(toolchain.compilerTarget)})`,
        )
    }
    if (toolchain.flags.length > 0) {
        const flags = cmakeQuote(toolchain.flags.join(' '))
        lines.push(
            `set(CMAKE_C_FLAGS_INIT ${flags})`,
            `set(CMAKE_CXX_FLAGS_INIT ${flags})`,
        )
    }
    lines.push(
        `set(CMAKE_AR ${cmakeQuote(programs.ar)})`,
        `set(CMAKE_RANLIB ${cmakeQuote(programs.ranlib)})`,
        `set(CMAKE_STRIP ${cmakeQuote(programs.strip)})`,
        '',
        // Not CMAKE_SYSROOT: the Debian cross layout keeps headers and libraries
        // in /usr/<triple>/{include,lib}, which isn't a sysroot the compiler can use.
        `set(CMAKE_FIND_ROOT_PATH ${cmakeQuote(sysroot)})`,
        'set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)',
        'set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)',
        'set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)',
        'set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)',
    )
    if (emulator !== null) {
        lines.push(
            '',
            `set(CMAKE_CROSSCOMPILING_EMULATOR ${cmakeQuote(emulator.join(';'))})`,
        )
    }
    return lines.join('\n') + '\n'
}

function mesonString(value: string): string {
    return `'${value.replace(/[\\']/g, '\\$&')}'`
}

function mesonArray(values: string[]): string {
    return `[${values.map(mesonString).join(', ')}]`
}

export function mesonCrossFile(setup: Setup): string {
    const { target, toolchain } = setup
    const emulator = emulatorCommand(setup)
    const { programs } = toolchain
    const lines = [
        `# Generated by cross-compile-action for ${target.triple}: ${target.name}`,
        '[binaries]',
        `c = ${mesonArray(compilerCommand(toolchain, programs.cc))}`,
        `cpp = ${mesonArray(compilerCommand(toolchain, programs.cxx))}`,
        `ar = ${mesonString(programs.ar)}`,
        `ranlib = ${mesonString(programs.ranlib)}`,
        `strip = ${mesonString(programs.strip)}`,
    ]
    if (emulator !== null) {
        lines.push(`exe_wrapper = ${mesonArray(emulator)}`)
    }
    lines.push(
        '',
        '[host_machine]',
        "system = 'linux'",
        `cpu_family = ${mesonString(target.mesonCpuFamily)}`,
        `cpu = ${mesonString(target.triple.split('-')[0])}`,
        `endian = ${mesonString(target.endian)}`,
    )
    return lines.join('\n') + '\n'
}

/** Environment for the `compile` and `run` scripts, and for later steps when exported */
export function environment(
    setup: Setup,
    files: GeneratedFiles,
): Record<string, string> {
    const { target, toolchain, sysroot, emulator } = setup
    const { programs } = toolchain
    const env: Record<string, string> = {
        CC: compilerCommand(toolchain, programs.cc).join(' '),
        CXX: compilerCommand(toolchain, programs.cxx).join(' '),
        AR: programs.ar,
        RANLIB: programs.ranlib,
        STRIP: programs.strip,
        CMAKE_TOOLCHAIN_FILE: files.toolchainFile,
        CROSS_TRIPLE: target.triple,
        CROSS_SYSROOT: sysroot,
    }
    if (emulator !== null) {
        env.QEMU_LD_PREFIX = sysroot
        if (emulator.cpu !== undefined) {
            env.QEMU_CPU = emulator.cpu
        }
    }
    return env
}
